"-----VUNDLE INIT----------
set nocompatible
set rtp+=/usr/local/opt/fzf
so ~/.vim/plugins.vim
so /usr/local/opt/fzf/plugin/fzf.vim
"-----END OF VUNDLE INIT----
syntax enable
filetype plugin indent on
let mapleader = ','             "Try to use comma as Leader key
set number			                "Activate line numbers
set backspace=indent,eol,start
set tabstop=2
set shiftwidth=2
set expandtab
set clipboard+=unnamedplus
set wildignore+=*/node_modules/*,*/.git/*

"---FOLDING----
"set foldenable
"set foldmethod=syntax

"---------PLUGIN SPECIFIC OPTIONS----
"let NERDTreeShowHidden=1
"let g:ctrlp_show_hidden=1
"indentLine
let g:indentLine_setColors=1
let g:indentLine_char = '¦'
let g:airline_theme='gruvbox'
let g:airline_solarized_bg='dark'
let g:gutentags_ctags_exclude = ["**/*.min.js", "**/*.min.css", "build", "vendor", ".git", "**/node_modules", "*.vim/bundle/*"]
let g:loaded_python3_provider=0
let g:loaded_python2_provider = 1
let g:NERDTreeWinPos = "right"
if executable('rg')
  set grepprg=rg\ --color=never
  let g:ctrlp_user_command = 'rg %s --files --color=never --glob ""'
  let g:ctrlp_use_caching = 0
endif
"-----------VISUALS----------------
"set guifont=Source\ Code\ Pro\ Medium:h17
set guifont=Consolas:h20
set t_CO=256
"remove scrollbars
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R
set colorcolumn=81
set scrolloff=999
set cursorline
set cursorcolumn
set background=dark
set autoread "autoreload files after changes
colorscheme Gruvbox
"highlight CursorLine guibg=#303000 ctermbg=238
"-----------SEARCH----------------
set incsearch
"-----------SPLIT MANAGEMENT----------------
nmap <C-J> <C-W><C-J>
nmap <C-H> <C-W><C-H>
nmap <C-K> <C-W><C-K>
nmap <C-L> <C-W><C-L>
"-----------MAPPINGS----------------
nmap <leader>ev :tabedit $MYVIMRC<cr>
nmap <leader>ap :tabedit ~/.vim/plugins.vim<cr>
nmap <leader>q  :NERDTreeToggle<cr>
nmap <C-R>	:CtrlPBufTag<cr>
nmap <leader>h :nohl<cr>
nmap <leader>fs :ts<space>
nmap <leader>ft :tag<space>
nnoremap <leader>. :CtrlPTag<cr>
nmap <leader>f :Files<cr>
nmap <leader>r :e %<cr>
nmap <c-p> :Files<cr>
au BufRead,BufNewFile *.arb set filetype=ruby
"----------AUTOCOMMANDS------------
"Automatically source vimrc file on save
augroup autosourcing
	autocmd!
	autocmd BufWritePost .vimrc source %
augroup END
"Strip trailing whitespaces on save by plugin
"https://github.com/bronson/vim-trailing-whitespace
augroup remove_trailing_whitespaces
  autocmd!
  autocmd BufWritePre * FixWhitespace
augroup END
"Unfold file when opening
augroup unfold_file
  autocmd!
  autocmd BufRead * normal zR
augroup END
